### ISSUE TITLE
ifconfig: ipnet_sysctl() failed

### ISSUE THREAD

**Issue by rainnus** [asadzia/VxWorks-VLAN#1]
I got an error when execute this line:
```
if (ipcom_sysctl(name, 6, IP_NULL, &if_data_len, IP_NULL, 0) < 0)
```
error message:
```
ifconfig: ipnet_sysctl() failed: Not a directory
```
how to fix it?

**Comment by rainnus** [comment]
Finally, I got the reason.  The predefined macros value of `IP_CTL_NET` is not right in my vxworks, which should be 4 rather than 3.

**Comment by asadzia** [comment]
Yes, that can vary in VxWorks. Good to hear that you figured it out. :))
